/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.2.1-11-g7f1450cc26"
#endif /* AVUTIL_FFVERSION_H */
